set_property PACKAGE_PIN J1 [get_ports {layer_0[5]}]
set_property PACKAGE_PIN L2 [get_ports {layer_0[4]}]
set_property PACKAGE_PIN J2 [get_ports {layer_0[3]}]
set_property PACKAGE_PIN G2 [get_ports {layer_0[2]}]
set_property PACKAGE_PIN H1 [get_ports {layer_0[1]}]
set_property PACKAGE_PIN K2 [get_ports {layer_0[0]}]
set_property PACKAGE_PIN H2 [get_ports {layer_1[5]}]
set_property PACKAGE_PIN G3 [get_ports {layer_1[4]}]
set_property PACKAGE_PIN A14 [get_ports {layer_1[3]}]
set_property PACKAGE_PIN A16 [get_ports {layer_1[2]}]
set_property PACKAGE_PIN B15 [get_ports {layer_1[1]}]
set_property PACKAGE_PIN B16 [get_ports {layer_1[0]}]
set_property PACKAGE_PIN A15 [get_ports {layer_2[5]}]
set_property PACKAGE_PIN A17 [get_ports {layer_2[4]}]
set_property PACKAGE_PIN C15 [get_ports {layer_2[3]}]
set_property PACKAGE_PIN C16 [get_ports {layer_2[2]}]
set_property PACKAGE_PIN K17 [get_ports {layer_2[1]}]
set_property PACKAGE_PIN M18 [get_ports {layer_2[0]}]
set_property PACKAGE_PIN N17 [get_ports {layer_3[5]}]
set_property PACKAGE_PIN P18 [get_ports {layer_3[4]}]
set_property PACKAGE_PIN L17 [get_ports {layer_3[3]}]
set_property PACKAGE_PIN M19 [get_ports {layer_3[2]}]
set_property PACKAGE_PIN P17 [get_ports {layer_3[1]}]
set_property PACKAGE_PIN R18 [get_ports {layer_3[0]}]
set_property PACKAGE_PIN W5 [get_ports clock_100]
set_property PACKAGE_PIN U16 [get_ports Found_match]
set_property PACKAGE_PIN W19 [get_ports reset]
set_property PACKAGE_PIN V17 [get_ports start_comparison]

set_property IOSTANDARD LVCMOS33 [get_ports Found_match]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_3[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_3[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_3[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_3[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_3[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {layer_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports start_comparison]
set_property IOSTANDARD LVCMOS33 [get_ports clock_100]
set_property DRIVE 12 [get_ports Found_match]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clock_100_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 6 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {layer_1_i[0]} {layer_1_i[1]} {layer_1_i[2]} {layer_1_i[3]} {layer_1_i[4]} {layer_1_i[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 6 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {layer_0_i[0]} {layer_0_i[1]} {layer_0_i[2]} {layer_0_i[3]} {layer_0_i[4]} {layer_0_i[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 6 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {layer_2_i[0]} {layer_2_i[1]} {layer_2_i[2]} {layer_2_i[3]} {layer_2_i[4]} {layer_2_i[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 6 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {layer_3_i[0]} {layer_3_i[1]} {layer_3_i[2]} {layer_3_i[3]} {layer_3_i[4]} {layer_3_i[5]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clock_100_IBUF_BUFG]
