webtalk_init -webtalk_dir C:/Users/rasmu/Documents/ExperimentalPhysics/FPGA_track_lab/MasterTrackMerged/MasterTrackMerged.sim/sim_1/behav/xsim/xsim.dir/MasterTrack_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jun  2 11:50:07 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0f9321f4-60a8-4dea-b9e8-f70c21283379" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "eaa5b6fbb69848b2a0c77c3a0216a8bb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4500U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2371 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.22_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6708_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1206582542 -regid "" -xml C:/Users/rasmu/Documents/ExperimentalPhysics/FPGA_track_lab/MasterTrackMerged/MasterTrackMerged.sim/sim_1/behav/xsim/xsim.dir/MasterTrack_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/rasmu/Documents/ExperimentalPhysics/FPGA_track_lab/MasterTrackMerged/MasterTrackMerged.sim/sim_1/behav/xsim/xsim.dir/MasterTrack_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/rasmu/Documents/ExperimentalPhysics/FPGA_track_lab/MasterTrackMerged/MasterTrackMerged.sim/sim_1/behav/xsim/xsim.dir/MasterTrack_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
